web:
    build: .
    volumes:
        - "app:/src/app"
    ports:
        - "80:3000"
    links:
        - redis
    environment:
        PORT: 443
        JWT_SECRET: SetJwtTokenSecretHere
        JWT_EXPIRES: 20160
        ADMIN_KEY: use_this_to_create_admin_user
        MANTA_URL: "https://us-east.manta.joyent.com"
        MANTA_USER: "websama"
        MANTA_KEY_ID: "3a:38:ed:ce:3d:c8:c7:4f:a4:ac:76:2a:4d:71:fb:c1"
redis:
    image: redis:latest
    ports:
        - "6379:6379"